#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

redcode_tree:
    resource: "@RedCodeTreeBundle/Resources/config/routing.yml"
    prefix: /admin

presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

home:
    path: /
    controller: App\Controller\HomeController::index
    options:
        breadcrumb:
            label: Home

contact:
    path: /contact
    controller: App\Controller\ContactController::index
    options:
        breadcrumb:
            label: Contact Us
            parent_route: home


med:
    path: /services/dash/med
    controller: App\Controller\MedlevelController::index
    options:
        breadcrumb:
            label: MAMIAS Services / Dashboard / Mediterranean Level
            parent_route: home

nat:
    path: /services/dash/nat
    controller: App\Controller\NationallevController::index
    options:
        breadcrumb:
            label: MAMIAS Services / Dashboard / National Level
            parent_route: home

search:
    path: /services/search
    controller: App\Controller\SearchController::index
    options:
        breadcrumb:
            label: MAMIAS Services / Searching / Serach MAMIAS
            parent_route: home

species_fiche:
    path: /services/search/{id}/show
    controller: App\Controller\SearchController::show
    options:
        breadcrumb:
            label: '%%species%%'
            parent_route: search


FAQ:
    path: /FAQ
    controller: App\Controller\FaqController::index
    options:
        breadcrumb:
            label: FAQ
            parent_route: home

CMS:
    path: /pages/{slug}
    #resource: "@OrbitaleCmsBundle/Controller/PageController::indexAction"
    options:
        breadcrumb:
            label: Contact Us
            parent_route: home


mamias_terms:
    path: /terms
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    terms.html.twig

mamias_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    privacy.html.twig
